baseURL = "https://scratchbuffer.net"
title = "ScratchBuffer"

languageCode = "en-us"

enableGitInfo = true

theme = "scratchbuffer"

tableOfContents = true
[markup.tableOfContents]
startLevel = 2
endLevel = 2
ordered = false

[params]
[params.site]
featuredPages = [
  "/topics/web-development/typescript-npm-setup-part-1/",
  "/topics/python/python-setup-linux/",
  "/topics/dev-tools/jetbrains-ide-launcher-script/",
]

[params.site.title]
[params.site.title.header]
textPrefix = "[[]]"

[markup]
[markup.highlight]
style = "friendly"

#[taxonomies]
#tag = "tags"
#disableKinds = ['taxonomy', 'term']

# gohugo.io/configuration/menus/
[menus]
[[menus.main]]
name = 'home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'topics'
pageRef = '/topics'
weight = 20

[[menus.main]]
name = 'tags'
pageRef = '/tags'
weight = 30

#[[menus.main]]
#name = 'Note Cards'
#pageRef = '/note-cards'
#weight = 30

#[[menus.main]]
#name = 'Section A'
#pageRef = '/section-a'
#weight = 20
#
#[[menus.main]]
#name = 'Section B'
#pageRef = '/section-b'
#weight = 30
#
#[[menus.main]]
#name = 'Section C'
#pageRef = '/section-c'
#weight = 40
#
#[[menus.main]]
#name = 'Tags'
#pageRef = '/tags'
#weight = 50

# Run minify to prevent Hugo template limitations from producing irregular whitespace;
# retain newlines in output in order to still have readable output during development.
#[minify]
#[minify.tdewolff]
#[minify.tdewolff.html]
#keepWhitespace = true